# Generated by Django 3.1 on 2023-03-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='note.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='notes', to='note.Tag', verbose_name='тег'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
    ]
