# Generated by Django 3.1 on 2023-03-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20230323_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата изменения')),
                ('image', models.ImageField(blank=True, default='media/default/default_item.png', null=True, upload_to='gallery/%Y/%m/%d', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'db_table': 'images',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='в наличии'),
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='notes', to='note.Image', verbose_name='изображение'),
        ),
    ]
