# Generated by Django 3.2.4 on 2023-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='note.Image', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, related_name='notes', to='note.Tag', verbose_name='тег'),
        ),
    ]
